### PR TITLE
Testing/service execution 20210531

### PR DESCRIPTION
**Pull request by cschu**

### CODE REVIEW

**Comment by lkuchenb** [comment]
I bumped the version in `develop`, please rebase

**Comment by lkuchenb** [comment]
@cschu the remaining issue was that the file `test_file_service_0.txt` was indeed already submitted, it is part of the `serviceexecutions` fixtureset which contains already completed service executions. There is an unsubmitted file, too, `test_file_unreferenced.txt`, I changed the success test accordingly.

For the remaining tests please cover also the case that the service was already executed and fails with a 403.

**Comment by cschu** [comment]
> @cschu the remaining issue was that the file `test_file_service_0.txt` was indeed already submitted, it is part of the `serviceexecutions` fixtureset which contains already completed service executions. There is an unsubmitted file, too, `test_file_unreferenced.txt`, I changed the success test accordingly.

Hm, I tried it with the unsubmitted one as well and that didn't work before.

> For the remaining tests please cover also the case that the service was already executed and fails with a 403.

That case is already in there, just commented out for tinkering with the `success` test.

**Review by lkuchenb — CHANGES_REQUESTED** [review]
Thanks, looks good to me!

Could you fix the mypy and flake errors? Then this is good to go.

**Comment by cschu** [comment]
`request_body: dict = test_data.get(testname, test_data["success"])` adding this into the function body to pass the `mypy` tests seems a bit ridiculous...

**Review by lkuchenb — APPROVED** [review]
Thanks! 👍  good to go

**Pull request merged**
