### PR TITLE
site_read can no longer read staged data; added test

### PR DESCRIPTION
**Pull request by cschu**
* cleanup of previous attempt
* prevents site_read users to access staged data
* integration test for file access still throws a TypeError (@KerstenBreuer : any idea?)

`TypeError: 'NoneType' object is not iterable

/usr/local/lib/python3.8/site-packages/openapi_core/unmarshalling/schemas/unmarshallers.py:149: TypeError`

### CODE REVIEW

**Comment by cschu** [comment]
The `test_file_download` integration test fails at the very same resource (`test_file_5`) that also causes problems with my test.

**Comment by KerstenBreuer** [comment]
@cschu, the reason why the test failed for default_file_5 is because that file is not submitted (https://github.com/ghga-de/datameta/blob/fix/issue354_on_develop/tests/integration/fixtures/default_files.json#L30). So it is expected that this download of this file by the admin (with site_read permissions) is failing. However, in the test the expected response code was 307 instead of 403. I fixed that and I also added a user that is neither site_admin nor group_admin but has site_read permissions.

**Comment by KerstenBreuer** [comment]
@cschu is the NoneType Error still occuring for you? I don't get it.

**Review by KerstenBreuer — APPROVED** [review]

**Comment by cschu** [comment]
> @cschu is the NoneType Error still occuring for you? I don't get it.

Yes, it is still there. The file test is not running as it is named `xtest...`.

**Comment by KerstenBreuer** [comment]
@cschu Oh I see. I look into it later today.

**Comment by KerstenBreuer** [comment]
@cschu, @lkuchenb bugs are resolved, can be merged

**Comment by cschu** [comment]
sweet, thanks! what was the issue?

**Comment by KerstenBreuer** [comment]
@lkuchenb `json=None` is used in quite some places across the code. Strangely it only made problems in this context. I kept it for now in the other places, but if a similar problem occurs at some point, you know the fix.

**Comment by lkuchenb** [comment]
@KerstenBreuer Thanks for digging into this. Dang. I've added this occasionally because otherwise the entire pyramid 40x HTML is always sent as a response body. Always found that a bit ugly for the endpoints that otherwise don't return HTML response bodies. But that was apparently not the right fix for that 😐

**Pull request merged**
