### PR TITLE
Feature/track used passwords 469b

### PR DESCRIPTION
**Pull request by cschu**

### CODE REVIEW

**Review by lkuchenb — CHANGES_REQUESTED** [review]
Looks good, minor comment inline and please add a test

**Comment by cschu** [comment]
@lkuchenb over to you

**Review by lkuchenb — CHANGES_REQUESTED** [review]
Looking good to me, just a remark on the test implementation: I suggest to change one of the users in the fixtures to have a previously set password (set to something obvious like `previous_password`) and to use that in the test rather than the `reuse_old` block.

**Review by lkuchenb — APPROVED** [review]
Good to go!

**Pull request merged**
